### ISSUE TITLE
is it possible to show the same data as Grid view

### ISSUE THREAD

**Issue by SelvaraniAlagumuthu** [zaguiini/react-native-final-tree-view#10]
Hi,
 is it possible to show the same data in same screen with different parameter navigation. like Gradpa as one screen if we click that grandpa it navigate to same screen and display Me ?.. like Windows folder tile structure.

**Comment by SnehalAgrawal** [comment]
It sounds like you want to do some Android Fragment type of thing. Can you please have a look at 
[How to Make a View Like Android Fragment in React Native](https://aboutreact.com/android-fragment-view/) ?
