### ISSUE TITLE
Invariant Violation: Element Type is Invalid

### ISSUE THREAD

**Issue by tolgaberk** [zaguiini/react-native-final-tree-view#12]
![Simulator Screen Shot - iPhone 11 - 2020-03-24 at 11 34 04](https://user-images.githubusercontent.com/32398085/77404867-6348ff00-6dc3-11ea-8dee-a29d33599d4f.png)

A few days ago it was working. but suddenly it just stopped.

**What did i try**
`yarn start --reset-cache` _didn't work_
`
rm -rf $TMPDIR/react-* &&
rm -rf $TMPDIR/metro-* &&
rm -rf $TMPDIR/haste-map-* &&
rm -rf node_modules/ &&
yarn cache clean --force
` _didn't do the trick_ 
`watchman watch-del-all` _and again nothing_

I Have created a new and clean project for this.
Just to know if some library causing the problem but it persisted.
I removed literally everything related to react-native except npm from my computer and then reinstalled but it didn't work.

**My environment info**

> System:
>     OS: macOS 10.15.3
>     CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
>     Memory: 167.72 MB / 16.00 GB
>     Shell: 5.7.1 - /bin/zsh
>   Binaries:
>     Node: 12.13.1 - /usr/local/bin/node
>     Yarn: 1.22.4 - /usr/local/bin/yarn
>     npm: 6.14.3 - /usr/local/bin/npm
>     Watchman: 4.9.0 - /usr/local/bin/watchman
>   SDKs:
>     iOS SDK:
>       Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
>     Android SDK:
>       API Levels: 28, 29
>       Build Tools: 28.0.3, 29.0.2
>       System Images: android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
>   IDEs:
>     Android Studio: 3.5 AI-191.8026.42.35.6010548
>     Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
>   npmPackages:
>     react: 16.9.0 => 16.9.0
>     react-native: 0.61.5 => 0.61.5
>   npmGlobalPackages:
>     react-native-cli: 2.0.1

**Comment by ReemaVinodGangdev** [comment]
@tolgaberk Hey, did you find the solution, got same error all of a sudden

**Comment by tolgaberk** [comment]
@ReemaVinodGangdev Nope, sorry but i forked another library which called `react-native-tree-select` and edited to fit my needs. If you want you can try mine or edit the original one.

**Comment by ReemaVinodGangdev** [comment]
@tolgaberk Thanks.

**Comment by spyreto** [comment]
I am facing the same issue....

**Comment by zaguiini** [comment]
Fixed in `v2.0.2`.
