### ISSUE TITLE
Unable to return view with height 80 for LIST.

### ISSUE THREAD

**Issue by Sudhir9026** [zaguiini/react-native-final-tree-view#15]
I am using this npm. but I found it is ok with only one line text for a node like **Grandpa**..., In my case, I wanted to pass a view with height 80.  but initially, it is not showing with 80 height but when click it increase the height.

Ex.
```


function App() {
  return (
    <TreeView
      data={family} // defined above
      renderNode={({ node, level, isExpanded, hasChildrenNodes }) => {
        return (
          <View style={{height: 80}}>
            <Text> THIS IS TITLE </Text>
            <Text> THIS IS SUBTITLE </Text>
          </View>
        )
      }}
    />
  )
}
```

**Comment by sureshcapternal** [comment]
I had same problem. Any solution ?

**Comment by Darcula666** [comment]
I had same problem. Any solution ?

**Comment by Darcula666** [comment]
I had same problem. Any solution ?

**Comment by sureshcapternal** [comment]
Add following props : 

getCollapsedNodeHeight={() => {
           // default size when node is closed
}}

Solved my problem.

**Comment by sureshcapternal** [comment]
> I had same problem. Any solution ?

getCollapsedNodeHeight={() => {
// default size when node is closed
}}
