### ISSUE TITLE
height: auto

### ISSUE THREAD

**Issue by tonhao-dev** [zaguiini/react-native-final-tree-view#21]
set the height to automatic in the following excerpt from the index.js file:
`
style={{
            height: isExpanded
              ? 'auto'
              : this.props.getCollapsedNodeHeight({
                  [this.props.idKey]: node[this.props.idKey],
                  level,
                }),
            zIndex: 1,
            overflow: 'hidden',
          }}
`

thus, the code will look like this:

`style={{
            height: 'auto',
            zIndex: 1,
            overflow: 'hidden',
          }}`

This helps to have more control over the current styling

**Comment by zaguiini** [comment]
What is the difference between your snippet and what we have on `master`?

**Comment by tonhao-dev** [comment]
With my snippet, we from dev side can set height with styled-components

**Comment by zaguiini** [comment]
But that's exactly what we have in the source code. Are you sure you pasted the correct snippet?
