### ISSUE TITLE
What kind of data structure should I pass to the component.

### ISSUE THREAD

**Issue by code-zyp1** [zaguiini/react-native-final-tree-view#25]
What kind of data structure should I pass to the component.
When I pass in a static array, it displays fine, but when I pass in my data from the server and cut it into the same format as the static array, an error occurs.
(undefined is not an object(evaluating 'nodes.map')
index.js :137
index.js 93

**Comment by zaguiini** [comment]
What is the name of the children property? Are you sure it's `children`? If it's not, you can pass a prop called `childrenKey` to the component.
