### ISSUE TITLE
Warning: componentWillReceiveProps is deprecated and will be removed in the next major version. Use static getDerivedStateFromProps instead.

### ISSUE THREAD

**Issue by SnehalAgrawal** [zaguiini/react-native-final-tree-view#4]
Hello Admin, Can you please update the library for the Warning: "componentWillReceiveProps is deprecated and will be removed in the next major version. Use static getDerivedStateFromProps instead."

**Comment by zaguiini** [comment]
PRs are open! You can do that if you want :) I don't have much time to do that, to be honest

**Comment by zaguiini** [comment]
Fixed on `v2`
