### ISSUE TITLE
Drop after refactoring

### ISSUE THREAD

**Issue by brightsider** [zaguiini/react-native-final-tree-view#7]
Why after version 2.0.0 state of the component was dropped after change of parent component state?

**Comment by zaguiini** [comment]
That was a design decision. But if you want to reimplement that behaviour, submit a PR modifying the condition inside componentDidUpdate. Put a flag there.

Another option would be to create a helper prop to check if the desired node should be expanded or not

**Comment by brightsider** [comment]
I'm already created PR.
But one more new issue with TextInput. After keyboard typed and state updated keyboard will dismiss.

**Comment by zaguiini** [comment]
Can't see the PR here
